# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosApp
    pod 'GoogleMLKit/BarcodeScanning', '3.2.0'
    pod 'GoogleMLKit/TextRecognition', '3.2.0'

end
